Rotulação - Botões coloridos e posicionamento dos elementos
cgisoftwares/Vision-JS pull request #10
Opened 2021-05-17 02:07 UTC by caiqueazevedo

- Adicionados 5 botões coloridos
- Ajuste na posição dos elementos

2021-05-17 15:48 UTC, devmorfeu approved these changes

2021-06-06 16:11 UTC, devmorfeu approved these changes

2021-06-06 16:14 UTC, IgorSSilveira requested changes

2021-06-06 16:14 UTC, IgorSSilveira commented on src/App.css
> +  --white-2: rgb(233, 233, 233);
Melhor colocar um nome que signifique o propósito da variável

2021-06-06 16:15 UTC, devmorfeu commented on src/App.css
> +  --white-2: rgb(233, 233, 233);
concordo

2021-06-06 16:38 UTC, devmorfeu approved these changes

2021-06-06 18:48 UTC, devmorfeu approved these changes

2021-06-06 18:51 UTC, caiqueazevedo commented on src/App.css
> +  --white-2: rgb(233, 233, 233);
Corrigido esquema de cores. Dêem uma olhada

2021-06-06 19:15 UTC, IgorSSilveira approved these changes
LGTM!

2021-06-06 19:20 UTC, merged